export const INDUSTRY_TYPES: string[] = [
  'Agriculture',
  'Arts And Design',
  'Automotive',
  'Construction',
  'Consulting',
  'Dairy (Milk)',
  'Education',
  'Engineering',
  'Electronics',
  'Financial Services',
  'FMCG',
  'Fruit And Vegetables',
  'Food Services (Restaurant, Cafe)',
  'Furniture',
  'Garment (Textile)',
  'General Store (Kirana)',
  'Gift Shop',
  'Government',
  'Hardware',
  'Healthcare',
  'Information Technology',
  'Jewellery',
  'Logistics (Transportation)',
  'Medicine (Pharma)',
  'Meat',
  'Metals And Mining',
  'Mobiles And Accessories',
  'Non Profit',
  'Oil And Gas',
  'Services',
  'Stationary',
  'Travel',
  'Others',
]
