export const TAX_RATES: string[] = [
  "none",
  "exempted",
  "0 @ IGST",
  "0.1 @ IGST",
  "0.25 @ IGST",
  "1.5 @ IGST",
  "3 @ IGST",
  "5 @ IGST",
  "6 @ IGST",
  "12 @ IGST",
  "13.8 @ IGST",
  "18 @ IGST",
  "28 @ IGST",
  "0 @ CGST/SGST",
  "0.1 @ CGST/SGST",
  "0.25 @ CGST/SGST",
  "1.5 @ CGST/SGST",
  "3 @ CGST/SGST",
  "5 @ CGST/SGST",
  "6 @ CGST/SGST",
  "12 @ CGST/SGST",
  "13.8 @ CGST/SGST",
  "18 @ CGST/SGST",
  "28 @ CGST/SGST",
];
